service:
  name: datastax

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

functions:
  process:
    handler: release/index.process
    events:
      - http:
          method: post
          path: process
