AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example RESTful service
Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./release
      Runtime: nodejs6.10
      Handler: index.process
      Events:
        EndPoint:
          Type: Api
          Properties:
            Path: /process
            Method: post

Outputs:
  endpoint:
    Description: "The API Gateway for Datastax."
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com' 